### ISSUE TITLE
bug(windows): Keyman not responsive and then keyboard lists not consistent

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5139]
**Describe the bug**

Recently, Keyman Developer 15.0.49 was installed on top of the latest stable without installing its corresponding Keyman for Windows (current stable 14.0.274).

There was a hiccup since the installation. Keyman for Windows stops responding. Switching keyboard has sometimes been ignored. When click to change the keyboard from the task bar, the keyboard shows to successfully change, but then all outputs are in Latin when typed in using the keyboard expected to output Khmer characters.

I then uninstalled Keyman Developer. To my surprise, some keyboards disappear from the keyboard menu accessed from the Keyman icon on the task bar. See the screenshot below.

![image](https://user-images.githubusercontent.com/28331388/119426298-2532cc80-bd33-11eb-8045-970652cd9b09.png)

[Diag Report](https://drive.google.com/file/d/1N1_F7PSlob8xf_GnKgU8pvka8UhabpJ3/view?usp=sharing)

**To Reproduce**

1. Ensure you have 14.0.274 of both Keyman Developer and for Windows
2. Install Keyman Developer 15.0.49 on top of 14.0.274
3. Restart if required, then start using Keyman for Windows
4. Choose a keyboard beside EN to type
5. See error - output Latin chars when typing in Chrome and Notepad
6. Uninstall Keyman Developer
7. Restart if required
8. Click on the Keyman icon and compare the keyboards listed there and in the configuration
9. See error - some keyboards in the configuration do not reflect in the keyboards listed in menu from the task bar

**Expected behavior**

Keyman for Desktop should keep working as expected without any hiccup when Keyman Developer is installed/updated/uninstalled.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman version: 14.0.274
 - Target Application: Chrome / Notepad

**Keyman Developer:**
 - Keyman Developer version: 15.0.49

**Comment by mcdurdin** [comment]
This should be resolved as we move to using Keyman Core in both products and Keyman Developer no longer has any dependency on Keyman for Windows.

**Comment by MakaraSok** [comment]
Thank you for that upcoming resolution. 

The problem I am trying to solve now is that the damage stays. I've uninstalled and reinstalled both Keyman Developer and Keyman for Windows to the latest stable, but the keyboard list still doesn't reflect the keyboards installed and exist in the configuration. 

Fresh installation has been done, but here is what I am stuck with:
![image](https://user-images.githubusercontent.com/28331388/119598196-b5911000-be0c-11eb-9ee1-ab44f3077880.png)

Khmer Angkor has been uninstalled together with all keyboards. It later was installed after Keyman for Windows was re-installed. 

I cannot use any Keyman keyboards now.

**Comment by mcdurdin** [comment]
Can you uninstall all Keyman programs, reboot, then reinstall 14.0.274 + your keyboards?

**Comment by MakaraSok** [comment]
Been there, done that and no help. The screenshot provided is what I currently stuck at.

**Comment by mcdurdin** [comment]
Resolved by uninstalling all Keyman and Keyman Developer; there were some locked 15.0 alpha files that were blocking the install.
